In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = np.array([2.5, 0.5, 2.2, 1.9, 3.1, 2.3, 2])
y = np.array([2.4, 0.7, 2.9, 2.2, 3.0, 2.7, 1.6])

In [3]:
cov_xy = np.cov(x,y)

In [4]:
cov_xy

array([[0.63571429, 0.58547619],
       [0.58547619, 0.67142857]])

In [5]:
eig_val, eig_vec =  np.linalg.eig(cov_xy)

In [6]:
eig_val

array([0.06782298, 1.23931988])

In [7]:
eig_vec

array([[-0.7178043 , -0.69624492],
       [ 0.69624492, -0.7178043 ]])

In [12]:
data = np.append(x.reshape(-1,1),y.reshape(-1,1),axis=1)

In [13]:
data

array([[2.5, 2.4],
       [0.5, 0.7],
       [2.2, 2.9],
       [1.9, 2.2],
       [3.1, 3. ],
       [2.3, 2.7],
       [2. , 1.6]])

In [16]:
pc = np.dot(data, eig_vec[1].T)

In [17]:
pc

array([ 0.01788198, -0.15434055, -0.54989365, -0.25630411,  0.00494635,
       -0.3367083 ,  0.24400296])

In [18]:
from sklearn.datasets import make_blobs

In [19]:
from sklearn.decomposition import PCA

In [21]:
data = make_blobs(n_samples=100, n_features=4)

In [29]:
type(data)

tuple

In [23]:
pc1 = PCA(n_components=1)

In [24]:
data_1_pc = pc1.fit_transform(data[0])

In [25]:
data_1_pc

array([[-3.16124621],
       [-7.54591161],
       [-3.41813546],
       [-4.26203881],
       [-2.26693043],
       [-6.01303772],
       [-5.45185714],
       [-6.69566366],
       [10.14761297],
       [-6.27087872],
       [-3.4818488 ],
       [-6.0543042 ],
       [-3.70204232],
       [ 9.64751229],
       [-2.93256708],
       [-4.09625618],
       [11.72487268],
       [ 9.59440128],
       [-6.0533205 ],
       [10.86109544],
       [ 8.65671487],
       [-2.21729088],
       [-5.29869846],
       [10.82664345],
       [ 9.91454658],
       [-6.42870387],
       [-5.39058189],
       [-6.1748092 ],
       [ 7.89730833],
       [-7.90605416],
       [ 9.05486052],
       [-3.30954904],
       [-3.8099073 ],
       [ 9.83280339],
       [-5.59408136],
       [-4.12792848],
       [-4.45874258],
       [-4.22469136],
       [-3.82198222],
       [-7.14196626],
       [-3.81909262],
       [-4.6826223 ],
       [-4.45044057],
       [-7.58315453],
       [-4.10276792],
       [-5

In [26]:
pc2 = PCA(n_components=2)

In [27]:
data_2_pc = pc2.fit_transform(data[0])

In [28]:
data_2_pc

array([[-3.16124621,  7.28556972],
       [-7.54591161, -4.55394761],
       [-3.41813546,  6.76189595],
       [-4.26203881, -4.24564665],
       [-2.26693043,  5.2705422 ],
       [-6.01303772, -3.59800196],
       [-5.45185714,  5.48698606],
       [-6.69566366, -4.57282282],
       [10.14761297, -1.73821618],
       [-6.27087872,  3.24369255],
       [-3.4818488 ,  6.02869253],
       [-6.0543042 , -5.29940512],
       [-3.70204232,  4.68197887],
       [ 9.64751229, -0.58473917],
       [-2.93256708,  6.06527637],
       [-4.09625618,  6.19889754],
       [11.72487268, -0.59183708],
       [ 9.59440128, -0.50648301],
       [-6.0533205 , -3.98016733],
       [10.86109544, -1.45638083],
       [ 8.65671487, -0.66510668],
       [-2.21729088,  7.01585998],
       [-5.29869846, -3.90882088],
       [10.82664345,  0.78816952],
       [ 9.91454658,  0.34322294],
       [-6.42870387, -5.36891646],
       [-5.39058189, -6.38967736],
       [-6.1748092 , -5.45779071],
       [ 7.89730833,

In [34]:
pc1.components_

array([[-0.54994894,  0.3967624 , -0.55541257,  0.48130306]])

In [36]:
pc2.components_

array([[-0.54994894,  0.3967624 , -0.55541257,  0.48130306],
       [-0.52389895,  0.12347726,  0.80966707,  0.2339284 ]])

In [37]:
pc1.explained_variance_

array([50.12126306])

In [38]:
pc2.explained_variance_

array([50.12126306, 21.45372976])